version: '3.8'

services:
  trading-bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
    restart: always
    volumes:
      - .:/app
